# Generated by Django 3.0.6 on 2020-06-03 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmeasurement',
            name='status',
            field=models.CharField(blank=True, choices=[('в', 'выполено'), ('н', 'не выполнено')], default='в', help_text='status measurement', max_length=1),
        ),
    ]
